redaction_rules:
- name: "Name and date redactor"
  redactor_type: "LLMTextRedaction"
  properties:
    model: "gpt-4.1-nano"
    system_prompt: "You will be sent text to analyse. Please find all strings in the text that adhere to the following rules: "
    redaction_terms:
    - "Find all human names in the text"
    - "Find all dates in the test"
provisional_redactions:
